DROP TABLE IF EXISTS `glpi_plugin_linesmanager_configs`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_profiles`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_ranges`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_numplans`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_lines`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_categories`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_extensionmobilities`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_forwards`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_timeslots`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_timeperiods`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_linegroups`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_algorithms`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_pickupgroups`;
DROP TABLE IF EXISTS `glpi_plugin_linesmanager_ddis`;
DELETE FROM `glpi_logs` WHERE itemtype like 'PluginLinesmanager%';